# Composicao do programa de teste do módulo mensagem utilizando o arcabouço 

[Diretorios]

Nome        =  TesteMensagem
PathDefault =  ..\Fontes\TesteMensagem
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes\TesteMensagem
h           =  ..\Fontes\TesteMensagem

[Modulos]
TestMen
Mensagem
Lista

[BuildInicio]
/OUT:..\Produto\TRAB4-4.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]